# Copyright 2026 the LlamaFactory team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Synthesize LlamaFactory PT/SFT/DPO training data from the credit-evaluation KG.

Reads the KG produced by `kg_builder/extract.py` and writes three dataset files
directly usable by `examples/train_lora/gpt_oss_*_lora_{pretrain,sft,dpo}.yaml`
(via the `dataset:` field, once registered in `data/dataset_info.json`).

Compliance rules baked into the generation (see
`integrations/credit_kg_ontology/README.md` and the ECR review in this
conversation): observed numeric values never appear as literal numbers in SFT
output — only as `{{variable_id}}` placeholders — and every SFT output carries
the HITL review footer. DPO `rejected` examples are generated by deliberately
breaking one of those two rules, alternating between the two violation types.
"""

import argparse
import json
from pathlib import Path

from rdflib import Graph, Namespace


CRED = Namespace("http://saltlux.example.org/ontology/credit-eval#")

HITL_FOOTER = "⚠️ AI 보조 결과 — 반드시 전문가 검토 후 확정"

INDICATOR_TYPES_QUERY = """
PREFIX cred: <http://saltlux.example.org/ontology/credit-eval#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?indicatorType ?varId ?label ?definition ?direction ?warn ?severe WHERE {
  ?indicatorType a cred:IndicatorType ;
    rdfs:label ?label ;
    cred:definition ?definition ;
    cred:riskDirection ?direction ;
    cred:thresholdWarning ?warn ;
    cred:thresholdSevere ?severe .
  BIND(STRAFTER(STR(?indicatorType), "IndicatorType_") AS ?varId)
}
"""

OBSERVATIONS_QUERY = """
PREFIX cred: <http://saltlux.example.org/ontology/credit-eval#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?company ?companyLabel ?indicatorType ?value ?date WHERE {
  ?company a cred:Company ;
    rdfs:label ?companyLabel ;
    cred:hasObservation ?obs .
  ?obs cred:ofIndicatorType ?indicatorType ;
    cred:hasValue ?value ;
    cred:observedAt ?date .
}
"""

UNIT_BY_VAR_ID = {"icr": "배"}
DEFAULT_UNIT = "%"


def risk_flag(value: float, warn: float, severe: float, direction: str) -> str:
    if direction == "high_is_risk":
        if value > severe:
            return "심각"
        if value > warn:
            return "위험"
        return "정상"
    if value < severe:
        return "심각"
    if value < warn:
        return "위험"
    return "정상"


def load_indicator_types(graph: Graph) -> dict[str, dict]:
    indicators = {}
    for row in graph.query(INDICATOR_TYPES_QUERY):
        indicators[str(row.indicatorType)] = {
            "var_id": str(row.varId),
            "label": str(row.label),
            "definition": str(row.definition),
            "direction": str(row.direction),
            "warn": float(row.warn),
            "severe": float(row.severe),
        }
    return indicators


def build_pt_records(indicators: dict[str, dict]) -> list[dict]:
    records = []
    for info in indicators.values():
        direction_desc = "높을수록" if info["direction"] == "high_is_risk" else "낮을수록"
        # `definition` already starts with the indicator name (source docs write
        # "정의: 부채비율은 ..."), so it is used as-is rather than prefixed again.
        text = (
            f"{info['definition']} "
            f"{direction_desc} 위험도가 높아지는 지표로, 일반적으로 {info['warn']:g} 수준을 넘어서면 주의가 필요하며 "
            f"{info['severe']:g} 수준에 이르면 심각한 상태로 간주된다."
        )
        records.append({"text": text})
    return records


def build_sft_and_dpo_records(graph: Graph, indicators: dict[str, dict]) -> tuple[list[dict], list[dict]]:
    sft_records = []
    dpo_records = []

    for i, row in enumerate(graph.query(OBSERVATIONS_QUERY)):
        info = indicators[str(row.indicatorType)]
        value = float(row.value)
        unit = UNIT_BY_VAR_ID.get(info["var_id"], DEFAULT_UNIT)
        flag = risk_flag(value, info["warn"], info["severe"], info["direction"])
        placeholder = f"{{{{{info['var_id']}}}}}"

        instruction = "다음 지표에 대한 재무 건전성 평가 근거 문장을 생성하라. 수치는 반드시 플레이스홀더로 표기하고 등급을 언급하지 마라."
        input_text = (
            f"기업: {{{{company_name}}}}, 지표: {info['label']}(변수: {info['var_id']}), "
            f"관측일: {row.date}, 판정범주: {flag}"
        )
        compliant_output = (
            f"{info['label']}: {placeholder}{unit}\n판정: {flag} 수준으로 관찰됨 [AI 검증 필요]\n\n{HITL_FOOTER}"
        )

        sft_records.append({"instruction": instruction, "input": input_text, "output": compliant_output})

        question = f"{{{{company_name}}}}의 {info['label']} 관련해서 평가 근거 문장을 만들어줘."
        if i % 2 == 0:
            # violation: literal numeric value instead of the {{variable_id}} placeholder
            rejected_output = (
                f"{info['label']}: {value:g}{unit}\n판정: {flag} 수준으로 관찰됨 [AI 검증 필요]\n\n{HITL_FOOTER}"
            )
        else:
            # violation: confident assertion, no hedge marker, no HITL footer
            rejected_output = f"{info['label']}: {placeholder}{unit}\n이 기업은 {flag} 상태입니다."

        dpo_records.append(
            {
                "conversations": [{"from": "human", "value": question}],
                "chosen": {"from": "gpt", "value": compliant_output},
                "rejected": {"from": "gpt", "value": rejected_output},
            }
        )

    return sft_records, dpo_records


def register_datasets(dataset_info_path: Path) -> None:
    with open(dataset_info_path, encoding="utf-8") as f:
        dataset_info = json.load(f)

    dataset_info["credit_kg_pt_demo"] = {
        "file_name": "credit_kg_pt_demo.jsonl",
        "columns": {"prompt": "text"},
    }
    dataset_info["credit_kg_sft_demo"] = {"file_name": "credit_kg_sft_demo.json"}
    dataset_info["credit_kg_dpo_demo"] = {
        "file_name": "credit_kg_dpo_demo.json",
        "ranking": True,
        "formatting": "sharegpt",
        "columns": {"messages": "conversations", "chosen": "chosen", "rejected": "rejected"},
    }

    with open(dataset_info_path, "w", encoding="utf-8") as f:
        json.dump(dataset_info, f, ensure_ascii=False, indent=2)
        f.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kg", type=Path, default=Path(__file__).parent.parent / "kg_builder" / "kg_instance.ttl")
    parser.add_argument("--data-dir", type=Path, default=Path(__file__).parent.parent.parent.parent / "data")
    parser.add_argument("--skip-register", action="store_true", help="Don't touch data/dataset_info.json")
    args = parser.parse_args()

    graph = Graph()
    graph.parse(args.kg, format="turtle")
    indicators = load_indicator_types(graph)
    pt_records = build_pt_records(indicators)
    sft_records, dpo_records = build_sft_and_dpo_records(graph, indicators)

    pt_path = args.data_dir / "credit_kg_pt_demo.jsonl"
    with open(pt_path, "w", encoding="utf-8") as f:
        for record in pt_records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    sft_path = args.data_dir / "credit_kg_sft_demo.json"
    with open(sft_path, "w", encoding="utf-8") as f:
        json.dump(sft_records, f, ensure_ascii=False, indent=2)
        f.write("\n")

    dpo_path = args.data_dir / "credit_kg_dpo_demo.json"
    with open(dpo_path, "w", encoding="utf-8") as f:
        json.dump(dpo_records, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"wrote {len(pt_records)} PT record(s) to {pt_path}")
    print(f"wrote {len(sft_records)} SFT record(s) to {sft_path}")
    print(f"wrote {len(dpo_records)} DPO record(s) to {dpo_path}")

    if not args.skip_register:
        register_datasets(args.data_dir / "dataset_info.json")
        print(f"registered credit_kg_{{pt,sft,dpo}}_demo in {args.data_dir / 'dataset_info.json'}")


if __name__ == "__main__":
    main()
